### ISSUE TITLE
Add open source link to footer. 

### ISSUE THREAD

**Issue by aljazceru** [HiveTalk/Roadmap#1]
not much more to say that what the title already expresses, when can we see the code for this?

**Comment by jurjendevries** [comment]
Yes, and curious to the license too. Please also link to the git from https://hivetalk.org/

**Comment by bitkarrot** [comment]
As soon as I clear up all the items on this list. 
I am not a full time dev, so not tomorrow but within a reasonable amount of time. 

https://github.com/HiveTalk/Roadmap

**Comment by bitkarrot** [comment]
Now open source

**Comment by jurjendevries** [comment]
> Now open source

Great job @bitkarrot ! What about promoting this at https://hivetalk.org/about or footer with a link to the git repo?

**Comment by bitkarrot** [comment]
Good Idea.  Lets stick it on the open Issues todo list. :)

**Comment by bitkarrot** [comment]
Done and will be on next release. 

<img width="1111" alt="Screenshot 2024-08-01 at 2 53 06 PM" src="https://github.com/user-attachments/assets/c86e9da4-dd64-4e14-83ad-9fe2ae7d7689">
