### ISSUE TITLE
Nostr login not working

### ISSUE THREAD

**Issue by jurjendevries** [HiveTalk/Roadmap#2]
We had a nice nostr dev talk by hivetalk, but nostr login (even npub) wasn't working for anyone. When using my Alby extension it showed that I wasn't using Nostr and gave me a random name, but also brought me to a screen to ask for a room name instead of using the room from the URL.

**Comment by bitkarrot** [comment]
seems to be universal 

https://bitkarrot.github.io/npublogin/

Add todo item to rewrite it and not use dependency from nostrband

**Comment by bitkarrot** [comment]
Issue is upstream from nostrband.  Change of plan: We'll continue to use nostr-login but put in a fail safe if nostrband has problems like yesterday. Its already a lot of code they have to maintain upstream and it is also in beta, so it does not make sense to do redundant work and add load to this project

**Comment by jurjendevries** [comment]
Thanks @bitkarrot I tried again today. It wasn't working well. There is a nostr icon on the right side of the screen, when I use this I am able to give my npub. But when joining a room, the screen stays dark for 10 seconds or so and thereafter I am seeing an window that it couldn't detect a nostr login and will use a random name. I hope the issue i solved soon, as the main advantage of hivetalk is using nostr.

**Comment by bitkarrot** [comment]
the Nostr icon on the right side of the screen should not be used for login, i think that's the cause of the problem. I will remove it today, as it seems to be the source of the issue from people trying to pre maturely login there.

If you are experiencing problems with the nostr-login module please also file an issue on https://github.com/nostrband/nostr-login

as this is the original code base that is handling the login feature. 

thanks. @jurjendevries

**Comment by bitkarrot** [comment]
Fwiw I have not even had time to work on the code base since last week, sorry as this is not my full time job....

**Comment by jurjendevries** [comment]
I can understand that if you don't have that many time it will took a while. I am already happy someone is trying this. Luckily it's working now, but still the Nostr icon on the right side is there. I've send you some zaps for the great work. Keep up the good work 🙏😃

**Comment by bitkarrot** [comment]
We fixed the front page one so we are keeping it now. Sorry for the reverse course, still figuring it out as we go. Thanks for the zaps!
